apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vitalam-api.fullname" . }}-config
  labels:
    {{- include "vitalam-api.labels" . | nindent 4 }}
data:
  port: {{ .Values.config.port | quote }}
  logLevel: {{ .Values.config.logLevel }}
  {{- if .Values.config.externalNodeHost }}
  nodeHost: {{ .Values.config.externalNodeHost }}
  {{- else if .Values.vitalamNode.enabled }}
  nodeHost: {{ template "vitalam-node.fullname" .Subcharts.vitalamNode }}
  {{- else if .Values.vitalamIpfs.vitalamNode.enabled }}
  nodeHost: {{ template "vitalam-ipfs-node.fullname" .Subcharts.vitalamIpfs }}
  {{- else }}
  {{- fail "Must supply either externalNodeHost or enable vitalamNode or vitalamIpfs" }}
  {{- end }}
  {{- if .Values.config.externalIpfsHost }}
  ipfsHost: {{ .Values.config.externalIpfsHost }}
  {{- else if .Values.vitalamIpfs.enabled }}
  ipfsHost: {{ template "vitalam-ipfs.fullname" .Subcharts.vitalamIpfs }}-api
  {{- end }}
  {{- if .Values.config.externalIpfsPort }}
  ipfsPort: {{ .Values.config.externalIpfsPort | quote }}
  {{- else if .Values.vitalamIpfs.enabled }}
  ipfsPort: {{ template "vitalam-ipfs.ipfsApiPort" .Subcharts.vitalamIpfs }}
  {{- end }}
  authJwksUri: {{ .Values.config.auth.jwksUri }}
  authAudience: {{ .Values.config.auth.audience }}
  authIssuer: {{ .Values.config.auth.issuer }}
  authTokenUrl: {{ .Values.config.auth.tokenUrl }}
