name: Run Lint and Tests

on: [pull_request]

jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 14.x
      - name: Install Packages
        run: npm install
      - name: Lint
        run: npm run lint
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 14.x
      - name: Install Packages
        run: npm install
      - name: Setup dependencies
        run: docker-compose -f docker-compose.yaml up -d
      - name: Sleep
        uses: kibertoad/wait-action@1.0.1
        with:
          time: '30s'
      - name: Run tests
        run: npm run test
